# Overview of MHQ schemes

```{r}

types <- read_types()

schemes <- read_schemes()

scheme_types <- read_scheme_types()

mhq_schemes <- schemes %>%
  filter(programme == "MHQ") %>%
  select(programme, scheme) %>%
  left_join(select(scheme_types, scheme, type), by = "scheme") %>%
  left_join(select(types, type, typeclass), by = "type")
```

```{r}
mhq_schemes %>%
  datatable(rownames = FALSE,
            filter = "top")
```


# Raw data

## INBOVEG data

```{r}
path_mhq_terr <- file.path(fileman_up("n2khab-mhq-data"), "processed/inboveg_mhq_terr")

path_mhq_terr_raw <- file.path(fileman_up("n2khab-mhq-data"), "raw/structure_variables")

path_extra_var <- file.path(fileman_up("n2khab-mhq-data"), "processed/extra_var_mhq")

classif_mhq_inbo <- get_type_inboveg(path_mhq_terr)

header_mhq_inbo <- get_header(path_mhq_terr)

site_qualifiers_moneos <- read_vc(file = "site_qualifiers_moneos", root = path_mhq_terr) %>%
  filter(str_detect(plot_id, "ZS")) %>%
  rename(record_id = recording_givid)

coordinates_91E0_sf <- read_vc(file = "coordinates_moneos_91E0_sf", root = path_mhq_terr)
structure_1330_da <- read_vc(file = "structure_mhq_1330_da", root = path_mhq_terr)
```

## Fieldmap data

```{r}

path_mhq_anb <- file.path(fileman_up("n2khab-mhq-data"), "processed/fieldmap_mhq")

classif_mhq_anb <- read_vc(root = path_mhq_anb, file = "type_observed")
assessments_mhq_anb <- read_vc(root = path_mhq_anb, file = "assessments")
structure_mhq_anb <- read_vc(root = path_mhq_anb, file = "structure_vars")
vegetation_mhq_anb <- read_vc(root = path_mhq_anb, file = "cover_species")
veglayers_mhq_anb <- get_cover_veglayers_fieldmap(path_mhq_anb)

pq_mhq_anb <- assessments_mhq_anb %>%
  distinct(plot_id, date_assessment, lsvi_measurement, dendro_record, cover_species_record) %>%
  filter(lsvi_measurement)
```

## VBI data

```{r}

path_vbi <- file.path(fileman_up("n2khab-mhq-data"), "processed/dwh_vbi")

standdescription_vbi <- read_vc(root = path_vbi, file = "stand_description")
date_vbi <- standdescription_vbi %>%
  distinct(plot_id, vbi_cycle, date = date_dendro)
missing_values_vbi <- read_vc(root = path_vbi, file = "missing_values") %>%
  filter(segment_id == 1)

#meest recent geobserveerde habitattype per meetpunt
classif_vbi <- read_vc(root = path_vbi, file = "type_observed_update")

classif_vbi_recent <- classif_vbi %>%
  rename(vbi_cycle = periode,
         type_observed = type) %>%
  group_by(plot_id) %>%
  filter(vbi_cycle == max(vbi_cycle)) %>%
  ungroup() %>%
  filter(str_sub(type_observed, 1, 2) == "91")

check <- classif_vbi_recent %>%
  group_by(plot_id, type_observed) %>%
  filter(n() > 1)
  
#van de meetpunten uit de 3de cyclus nemen we ook de meetpunten van de 2de cyclus en gaan we uit van hetzelfde habitattype
classif_vbi2_add <- classif_vbi_recent %>%
  filter(vbi_cycle == 3) %>%
  mutate(vbi_cycle = 2) %>%
  semi_join(standdescription_vbi, by = c("plot_id", "vbi_cycle"))

classif_vbi <- classif_vbi_recent %>%
  bind_rows(classif_vbi2_add) %>%
  mutate(type_observed = ifelse(type_observed == "9120_qb", "9120", type_observed)) %>%
  group_by(plot_id, vbi_cycle, type_observed, source, note_manual_check) %>%
  summarise(phab = sum(phab)) %>%
  ungroup() %>%
  left_join(date_vbi, by = c("plot_id", "vbi_cycle")) %>%
  left_join(missing_values_vbi, by = c("plot_id", "vbi_cycle")) %>%
  filter(!herb_missing_value & !dendro_missing_value) %>%
  mutate(survey = "vbi",
         ID = str_c(plot_id, "_", vbi_cycle),
         record_id_square = ID,
         record_id_circle = ID)

check <- classif_vbi %>%
  group_by(plot_id, vbi_cycle, type_observed) %>%
  filter(n() > 1)
```

## Merge ANB and INBO data

```{r}

pq_mhq_inbo <- header_mhq_inbo %>%
  filter(!survey %in% c("Schelde-estuarium")) %>%
  mutate(plot_type = ifelse(area %in% c(9, 256), "square",
                            ifelse(area > 1000, "circle", NA)),
         date = as.Date(vague_date_begin)) %>%
  left_join(site_qualifiers_moneos, by = c("survey", "record_id"))  %>%
  mutate(link_mhq = ifelse(!is.na(plot_id), plot_id, user_reference)) %>%
  select(survey, date, record_id, plot_type, link_mhq)

pq_moneos <- header_mhq_inbo %>%
  filter(survey %in% c("Schelde-estuarium")) %>%
  left_join(site_qualifiers_moneos, by = c("survey", "record_id")) %>%
  filter(!is.na(plot_id)) %>%
  semi_join(structure_1330_da, by = "plot_id") %>% #dit bestand bevat alle plots met 1330_da
  mutate(plot_type = "square",
         date = as.Date(vague_date_begin)) %>%
  select(survey, date, record_id, plot_type, link_mhq = plot_id) 

pq_mhq_inbo <- pq_mhq_inbo %>%
  bind_rows(pq_moneos)

pq_mhq_inbo_wide <- pq_mhq_inbo %>%
  filter(!is.na(plot_type)) %>%
  pivot_wider(names_from = "plot_type", values_from = "record_id", names_prefix = "record_id_") %>%
  mutate(ID = str_c(link_mhq, "_", date))

classif_1330_da <- pq_moneos %>%
  distinct(survey, record_id) %>%
  mutate(type_observed = "1330_da",
         type_cover = 100)

classif_mhq_inbo <- classif_mhq_inbo %>%
  bind_rows(classif_1330_da) %>%
  left_join(select(pq_mhq_inbo, record_id, plot_type), by = "record_id") %>%
  filter(plot_type == "square") %>%
  rename(record_id_square = record_id) %>%
  left_join(pq_mhq_inbo_wide, by = c("survey", "record_id_square"))

pq_mhq_anb <- pq_mhq_anb %>%
  mutate(ID = str_c(plot_id, "_", date_assessment),
         survey = "anb") %>%
  select(survey, date = date_assessment, ID, link_mhq = plot_id) %>%
  mutate(record_id_square = ID,
         record_id_circle = ID)
  
classif_mhq_anb <- classif_mhq_anb %>%
  filter(segment_id == 1) %>%
  mutate(type_observed = ifelse(!is.na(type_observed_square), type_observed_square, type_observed_circle),
         ID = str_c(plot_id, "_", date_assessment),
         plot_type = "square",
         survey = "anb") %>%
  select(ID, survey, type_observed, plot_type) %>%
  inner_join(pq_mhq_anb, by = c("survey", "ID"))

type_info <- types %>%
  group_by(main_type) %>%
  mutate(has_subtypes = any(typelevel == "subtype")) %>%
  ungroup() %>%
  select(type_observed = type, typelevel, has_subtypes)

classif_mhq <- classif_mhq_inbo %>%
  bind_rows(classif_mhq_anb) %>%
  select(survey, ID, record_id_square, record_id_circle, link_mhq, date, type_observed, plot_type, type_cover) %>%
  left_join(type_info, by = "type_observed") %>%
  mutate(is_type_target = type_observed %in% mhq_schemes$type,
         is_maintype_target = str_sub(type_observed, 1, 4) %in% str_sub(mhq_schemes$type, 1, 4),
         subtype_defined = !(has_subtypes & typelevel == "main_type")) %>%
  group_by(ID) %>%
  mutate(any_type_target = any(is_type_target),
         n_type_target = sum(is_type_target),
         cover_target = sum(type_cover * is_type_target),
         type_cover_all = str_c(str_c(type_cover, "% ", type_observed), collapse = "; ")) %>%
  ungroup() %>%
  filter(is_maintype_target)

data_habitat <- classif_mhq %>%
  select(ID, survey, record_id_square, record_id_circle, link_mhq, date, type_observed, subtype_defined, type_cover, type_cover_all)
  
```

