# Overzicht resultaten

```{r}

habcat <- data.frame(habcat_code = c("gr_bm", "cd", "hs_id", "fs", "sw", "rw"),
                     habcat_name = c("grassland_marsh", "coastal_dunes", "heath_inland_dunes", "forests", "standing_water", "streams"))

status_flanders <- NULL
trend_flanders <- NULL

for (i in 1:nrow(habcat)) {
  
  input_path <- file.path(fileman_up("n2khab-mhq-data"), str_c("processed/lsvi_mhq/", habcat$habcat_name[i],"/result"))
  
  status_flanders_habcat  <- read_vc(root = input_path,
           file = str_c("status_habitat_", habcat$habcat_code[i]))
  
  trend_flanders_habcat <- read_vc(root = input_path,
           file = str_c("trend_habitat_", habcat$habcat_code[i])) %>%
    filter(parameter == "verschil_aandeel_gunstig_abs")
  
  status_flanders <- status_flanders %>%
    bind_rows(status_flanders_habcat)
  
  trend_flanders <- trend_flanders %>%
    bind_rows(trend_flanders_habcat)
  
}

status_plot <- NULL

habcat_terr <- habcat %>%
  filter(! habcat_name %in% c("streams", "standing_water"))

for (i in 1:nrow(habcat_terr)) {
  
  input_path <- file.path(fileman_up("n2khab-mhq-data"), str_c("processed/lsvi_mhq/", habcat$habcat_name[i],"/result"))
  
  status_plot_habcat  <- read_vc(root = input_path,
           file = str_c("lsvi_plot_", habcat$habcat_code[i]))
  
  status_plot <- status_plot %>%
    bind_rows(status_plot_habcat)
  
}

status_plot_sf <- status_plot %>%
  st_as_sf(coords = c("x", "y"), crs = 31370)

status_plot_sf %>%
  mutate(show_color = ifelse(lsvi == "gunstig", "green", "blue")) %>%
  st_transform(4326) %>%
  leaflet() %>%
  addTiles() %>%
  addCircleMarkers(color = ~show_color)

status_plot_sf %>%
  st_write("../output/meetnet_habitatkwaliteit_lsvi_meetpunt.gpkg")
```

```{r}
status_stream  <- read_vc(root = file.path(fileman_up("n2khab-mhq-data"), str_c("processed/lsvi_mhq/streams/result")),
           file = "lsvi_plot_rw")

status_stream_sf <- status_stream %>%
  st_as_sf(coords = c("x", "y"), crs = 31370)

status_stream_sf %>%
  mutate(show_color = ifelse(lsvi == "gunstig", "green", "blue")) %>%
  st_transform(4326) %>%
  leaflet() %>%
  addTiles() %>%
  addCircleMarkers(color = ~show_color)
```

```{r}
status_ws  <- read_vc(root = file.path(fileman_up("n2khab-mhq-data"), str_c("processed/lsvi_mhq/standing_water/result")),
           file = "lsvi_watersurface_sw")

status_ws_sf <- watersurfaces_hab$watersurfaces_polygons %>%
  select(code_watersurfaces = polygon_id) %>%
  inner_join(status_ws, by = "code_watersurfaces")

status_ws_sf %>%
  mutate(show_color = ifelse(lsvi == "gunstig", "green", "blue")) %>%
  st_transform(4326) %>%
  leaflet() %>%
  addTiles() %>%
  addPolygons(color = ~show_color)
```

```{r}
status_plot_sf %>%
  st_write(dsn = "../output/meetnet_habitatkwaliteit_lsvi_meetpunt.gpkg", layer = "terrestrisch", delete_dsn = TRUE)

status_stream_sf %>%
  st_write(dsn = "../output/meetnet_habitatkwaliteit_lsvi_meetpunt.gpkg", layer = "aquatisch_rivieren")

status_ws_sf %>%
  st_write(dsn = "../output/meetnet_habitatkwaliteit_lsvi_meetpunt.gpkg", layer = "aquatisch_plassen")
```



```{r}
#2170 volledig in SBZH: schatting VL = schatting in SBZH
add_2170_sbzh <- status_flanders %>% 
  filter(habitattype == "2170") %>%
  mutate(sbzh = "Binnen")

status_flanders <- status_flanders %>%
  bind_rows(add_2170_sbzh) %>%
  filter(habitattype != "9110") %>%
  mutate(type_resultaat = factor(type_resultaat, levels = c("Habitattype", "SBZH", "Habitatsubtype"))) %>%
  arrange(habitattype, type_resultaat, habitatsubtype) %>%
  filter(!(habitatsubtype == "2190_a" & type_resultaat %in% c("Habitattype", "SBZH")))

write_csv2(status_flanders, "../output/status_habitatkwaliteit.csv")

trend_flanders <- trend_flanders %>%
  mutate(type_resultaat = factor(type_resultaat, levels = c("Habitattype", "SBZH", "Habitatsubtype"))) %>%
  arrange(habitattype, type_resultaat, habitatsubtype)

trend_flanders %>%
  filter(parameter == "verschil_aandeel_gunstig_abs") %>%
write_csv2("../output/trend_habitatkwaliteit.csv")
```

```{r}

habcat <- data.frame(habcat_code = c("gr_bm", "cd", "hs_id", "fs", "sw"),
                     habcat_name = c("grassland_marsh", "coastal_dunes", "heath_inland_dunes", "forests", "standing_water"))

status_beheer <- NULL

for (i in 1:nrow(habcat)) {
  
  input_path <- file.path(fileman_up("n2khab-mhq-data"), str_c("processed/lsvi_mhq/", habcat$habcat_name[i],"/result"))
  
  beheer_habcat  <- read_vc(root = input_path,
           file = str_c("status_beheer_", habcat$habcat_code[i]))
  
  status_beheer <- status_beheer %>%
    bind_rows(beheer_habcat)
  
}

status_beheer <- status_beheer %>%
  select(-starts_with("opp")) %>%
  arrange(habitattype, passend_beheer)

write_csv2(status_beheer, "../output/status_habitat_beheer.csv", na = "")
```


```{r}
status_flanders %>%
  arrange(habitattype) %>%
  datatable(rownames = FALSE,
            filter = "top",
            caption = "Aandeel habitat met gunstige toestand (\\%)")
```

```{r, fig.height=7, fig.width=8}

beoordeling_colors <- c("Goed" = inbo_lichtgroen, "Niet goed" = inbo_rood, "Onbekend" = inbo_grijs)

status_flanders %>%
  mutate(beoordeling = factor(beoordeling, levels = c("Goed", "Niet goed", "Onbekend"))) %>%
  filter(type_resultaat %in% c("Habitattype", "SBZH")) %>%
  filter(sbzh != "Buiten") %>%
  mutate(schaal = ifelse(sbzh == "Binnen", "Binnen SBZH", "Vlaanderen"),
         schaal = factor(schaal, levels = c("Vlaanderen", "Binnen SBZH"))) %>%
  ggplot(aes(x = habitattype, y = aandeel_gunstig/100, ymin = aandeel_gunstig_llci/100, ymax = aandeel_gunstig_ulci/100, colour = beoordeling, label = n_obs)) +
  geom_point(size = 5, show.legend = TRUE) +
  geom_errorbar(width = 0.2, show.legend = TRUE) +
  geom_hline(yintercept = 0.75, linetype = 2) +
 # geom_hline(yintercept = 0.9, linetype = 2) +
  geom_text(nudge_y = 0.05, nudge_x = 0.4 ,colour = "black", size = 3) +
  facet_wrap(~ schaal) +
  labs(x = "Habitattype", y = "Aandeel habitat in goede toestand", colour = "Beoordeling") +
  scale_color_manual(values = beoordeling_colors, drop = FALSE) +
  scale_x_discrete(limits = rev) +
  scale_y_continuous(labels = scales::percent, limits = c(0,1)) +
  coord_flip() +
  theme(legend.position = "bottom")

ggsave("../output/toestand_habitatkwaliteit_2025-02-05.png")
```
```{r, fig.height=7, fig.width=8}

beoordeling_colors <- c("Goed" = inbo_lichtgroen, "Niet goed" = inbo_rood, "Onbekend" = inbo_grijs)

status_flanders %>%
  mutate(beoordeling = factor(beoordeling, levels = c("Goed", "Niet goed", "Onbekend"))) %>%
  filter(type_resultaat %in% c("Habitattype", "SBZH")) %>%
  mutate(schaal = ifelse(sbzh == "Binnen", "Binnen SBZH",
                        ifelse(sbzh == "Buiten", "Buiten SBZH", "Vlaanderen")),
         schaal = factor(schaal, levels = c("Vlaanderen", "Binnen SBZH", "Buiten SBZH"))) %>%
  ggplot(aes(x = habitattype, y = aandeel_gunstig/100, ymin = aandeel_gunstig_llci/100, ymax = aandeel_gunstig_ulci/100, colour = beoordeling, label = n_obs)) +
  geom_point(size = 5, show.legend = TRUE) +
  geom_errorbar(width = 0.2, show.legend = TRUE) +
  geom_hline(yintercept = 0.75, linetype = 2) +
 # geom_hline(yintercept = 0.9, linetype = 2) +
  geom_text(nudge_y = 0.05, nudge_x = 0.4 ,colour = "black", size = 3) +
  facet_wrap(~ schaal) +
  labs(x = "Habitattype", y = "Aandeel habitat in goede toestand", colour = "Beoordeling") +
  scale_color_manual(values = beoordeling_colors, drop = FALSE) +
  scale_x_discrete(limits = rev) +
  scale_y_continuous(labels = scales::percent, limits = c(0,1)) +
  coord_flip() +
  theme(legend.position = "bottom")

ggsave("../output/toestand_habitatkwaliteit_2024.png")
```

```{r}
trend_flanders %>%
  arrange(habitattype) %>%
  select(-parameter) %>%
  datatable(rownames = FALSE,
            filter = "top",
            caption = "Absoluut verschil in aandeel habitat in goede toestand")
```
```{r, fig.height=7, fig.width=8}

klasse_color <- c(rev(traffic_palette(7)), "grey65", "grey35", "grey50") %>%
  setNames(
    c("++", "+", "+~", "~", "-~", "-", "--", "?+", "?-", "?")
  ) 
klasse_color[4] <- inbo_steun_blauw

trend_flanders %>%
  filter(habitattype != "9110") %>%
  filter(parameter == "verschil_aandeel_gunstig_abs") %>%
  filter(sbzh != "Buiten") %>%
  filter(type_resultaat %in% c("Habitattype", "SBZH")) %>%
  mutate(schaal = ifelse(sbzh == "Binnen", "Binnen SBZH", "Vlaanderen"),
         schaal = factor(schaal, levels = c("Vlaanderen", "Binnen SBZH"))) %>%
  ggplot(aes(x = habitattype, y = mean/100, ymin = llci_0.95/100, ymax = ulci_0.95/100, label = klasse, colour = klasse)) +
  geom_point(size = 7) +
  geom_errorbar(width = 0.2, show.legend = TRUE) +
  geom_hline(yintercept = 0, linetype = 2) +
  geom_hline(yintercept = c(-0.12, 0.12), linetype = 3) +
  geom_text(size = 4, colour = "white") +
  labs(y = "Absoluut verschil aandeel habitat gunstig (%)",
       x = "Habitattype") +
  facet_wrap(~ schaal) +
  scale_x_discrete(limits = rev) +
  scale_y_continuous(labels = scales::percent, limits = c(-0.80,0.80)) +
  scale_colour_manual(values = klasse_color, labels = class_labels(lang = "nl")) +
  labs(colour = "Interpretatie trend") +
  coord_flip() +
  theme(legend.position = "bottom")

ggsave("../output/trend_habitatkwaliteit.png")

```
