---
title: "Figuren rapport"
output: html_document2
---

```{r, include = FALSE}
library(tidyverse)
library(INBOtheme)
library(git2rdata)
library(n2khab)
library(n2khabmon)
library(effectclass)
conflicted::conflicts_prefer(dplyr::filter)
```


# Figuren rapport

```{r}
habcat_name <- "grassland_marsh"
habcat_code <- "gr_bm"

input_path <- file.path(fileman_up("n2khab-mhq-data"), str_c("processed/lsvi_mhq/", habcat_name,"/result"))

beoordeling_colors <- c("Gunstig" = inbo_lichtgroen, "Ongunstig" = inbo_rood, "Onbekend" = inbo_grijs)
```

## Beoordeling van de regionale toestand en trend

### Regionale toestand

```{r}

status_flanders  <- read_vc(root = input_path,
           file = str_c("status_habitat_", habcat_code)) %>%
  filter(habitattype %in% c("6230", "6410", "6510"))

```

```{r figtoestand}

beoordeling_colors <- c("Goed" = inbo_lichtgroen, "Niet goed" = inbo_rood, "Onbekend" = inbo_grijs)

status_flanders %>%
  filter(type_resultaat %in% c("Habitattype", "SBZH")) %>%
  filter(sbzh != "Buiten") %>%
  mutate(schaal = ifelse(sbzh == "Binnen", "Binnen SBZ-H", "Vlaanderen"), #SBZ-H ipv SBZH conform tekst in caption
         schaal = factor(schaal, levels = c("Vlaanderen", "Binnen SBZ-H"))) %>%
  ggplot(aes(x = habitattype, y = aandeel_gunstig/100, ymin = aandeel_gunstig_llci/100, ymax = aandeel_gunstig_ulci/100, colour = beoordeling)) +
  geom_point(size = 3, show.legend = TRUE) + #show.legend = TRUE om alle categorieën te tonen
  geom_errorbar(width = 0.2, show.legend = TRUE) +
  geom_hline(yintercept = 0.75, linetype = 2) +
  facet_wrap(~ schaal) +
  labs(x = "Habitattype", y = "Aandeel habitat in goede toestand", colour = "Beoordeling") +
  scale_color_manual(values = beoordeling_colors, drop = FALSE) +
  scale_x_discrete(limits = rev) +
  scale_y_continuous(labels = scales::percent, limits = c(0,1)) +
  coord_flip()
  
```
### Regionale trend

```{r }

lsvi_habitat_trend <- read_vc(root = input_path,  file = str_c("trend_habitat_", habcat_code))  %>%
  filter(habitattype %in% c("6230", "6410", "6510"))
```

```{r figtrend}

lsvi_habitat_trend %>%
  filter(parameter == "verschil_aandeel_gunstig_abs") %>%
  filter(sbzh != "Buiten") %>%
  filter(type_resultaat %in% c("Habitattype", "SBZH")) %>%
  mutate(schaal = ifelse(sbzh == "Binnen", "Binnen SBZ-H", "Vlaanderen"),
         schaal = factor(schaal, levels = c("Vlaanderen", "Binnen SBZ-H"))) %>%
  ggplot(aes(x = habitattype, y = mean/100, ymin = llci_0.95/100, ymax = ulci_0.95/100,
             width = 0.2)) +
  stat_effect(reference = 0, 
              threshold = c(-0.12, 0.12) ,
              show.legend = TRUE,
              labels = class_labels(lang = "nl")
              ) +
  labs(y = "Absoluut verschil aandeel habitat in goede toestand",
       x = "Habitattype",
       colour = "Interpretatie trend") +
  facet_wrap(~ schaal) +
  scale_x_discrete(limits = rev) +
  scale_y_continuous(labels = scales::percent, limits = c(-0.70,0.70)) +
  coord_flip()
```

## Beoordeling per LSVI-indicator

### Toestand per LSVI-inidcator

```{r}

status_indicatoren <- read_vc(root = input_path,
           file = str_c("status_indicatoren_", habcat_code)) %>%
  filter(habitattype %in% c("6230", "6410", "6510"))
```

```{r}

for (habt in unique(status_indicatoren$habitattype)) {
  
  plot_ht <- status_indicatoren %>%
  filter(habitattype == habt) %>%
  filter(type_resultaat %in% c("Habitattype")) %>%
  mutate(belang = ifelse(belang == "b", "Belangrijk",
                         ifelse(belang == "zb", "Zeer belangrijk", NA))) %>%
  ggplot(aes(x = indicator, 
             y = aandeel_gunstig/100, 
             shape = belang,
             ymin = aandeel_gunstig_llci/100, 
             ymax = aandeel_gunstig_ulci/100,
         colour = beoordeling)) + 
  geom_point(size = 4, alpha = 0.8) +
  geom_errorbar(width = 0.2, alpha = 0.8) +
  facet_grid(criterium ~ habitattype, scales = "free_y", space = "free") + 
  coord_flip() +
  labs(x = "Indicator",
       y = "Aandeel habitat in goede toestand per indicator",
       colour = "Beoordeling",
       shape = "Belang indicator") + 
  geom_hline(aes(yintercept = 0.75), 
             colour = "black", 
             size = 0.5, 
             linetype = "dashed", 
             alpha = 0.5)  +
   scale_color_manual(values = beoordeling_colors, drop = FALSE) +
  theme(strip.text.y = element_text(angle = 0)) +
  scale_y_continuous(labels = scales::percent, limits = c(0,1))
  
  plot(plot_ht)
  
}

```



### Trend per LSVI-indicator

#### Trend van het aandel habitat in goede toestand per indicator

```{r}

lsvi_indicator_trend <- read_vc(root = input_path,  file = str_c("trend_indicatoren_", habcat_code)) %>%
  filter(habitattype %in% c("6230", "6410", "6510"))
```

```{r}

for (ht in unique(lsvi_indicator_trend$habitattype)) {
  
  plot <- lsvi_indicator_trend %>%
    filter(habitattype == ht) %>%
    filter(parameter == "verschil_aandeel_gunstig_abs") %>%
    mutate(belang = ifelse(belang == "b", "belangrijk",
                           ifelse(belang == "zb", "zeer belangrijk", NA))) %>%
    ggplot(aes(x = indicator, y = mean/100, ymin = llci_0.95/100, ymax = ulci_0.95/100,
               shape = belang, width = 0.2)) +
    stat_effect(reference = 0, 
                threshold = c(-0.12, 0.12),
                labels = class_labels(lang = "nl"),
                show.legend = TRUE
                ) +
    labs(y = "Absoluut verschil aandeel habitat in goede toestand per indicator",
         x = "Indicator",
         colour = "Interpretatie trend",
         shape = "Belang indicator") +
    facet_grid(criterium ~ habitattype, scales = "free", space = "free") +
    scale_x_discrete(limits = rev) +
    scale_y_continuous(labels = scales::percent, limits = c(-1,1)) +
    coord_flip() +
    theme(strip.text.y = element_text(angle = 0)) +
    guides(shape = guide_legend(override.aes = aes(label = "")))
  
  plot(plot)
  
}

```

#### Trend van de kwaliteitsindex per indicator


```{r}

trend_index_ind <- read_vc(root = input_path,  file = str_c("trend_index_ind_", habcat_code)) %>%
  filter(habitattype %in% c("6230", "6410", "6510"))
```

```{r}

labels_kwaliteitindex <- class_labels(lang = "nl") %>%
  str_replace("toename", "verbetering") %>%
  str_replace("afname", "achteruitgang")

for (ht in unique(trend_index_ind$habitattype)) {
  
  plot_ht <- trend_index_ind %>%
  filter(habitattype == ht) %>%
  filter(type_resultaat %in% c("Habitattype")) %>%
    mutate(belang = ifelse(belang == "b", "belangrijk",
                           ifelse(belang == "zb", "zeer belangrijk", NA))) %>%
  ggplot(aes(x = indicator, 
             y = index_diff_mean, 
             ymin = index_diff_llci_0.95, 
             ymax = index_diff_ulci_0.95,
             shape = belang,
             width = 0.2)) + 
    stat_effect(reference = 0, 
                threshold = c(-0.1, 0.1),
                labels = labels_kwaliteitindex,
                show.legend = TRUE
                ) +
    labs(y = "Gemiddeld verschil kwaliteitsindex",
         x = "Indicator",
         colour = "Interpretatie trend",
         shape = "Belang indicator") +
    facet_grid(criterium ~ habitattype, scales = "free", space = "free") +
    lims(y = c(-1.5, 1.5)) +
    scale_x_discrete(limits = rev) +
    coord_flip() +
    theme(strip.text.y = element_text(angle = 0)) +
    guides(shape = guide_legend(override.aes = aes(label = ""),
                                order = 1))
  
  plot(plot_ht)
  
}

```


